name: Build

on: push

permissions:
  contents: read

jobs:
  build:
    name: Build TexModAutomator binary
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download AutoIt v3
      run: Invoke-WebRequest -Uri https://www.autoitscript.com/files/autoit3/autoit-v3.zip -OutFile autoit-v3.zip
    - name: Extract files from the AutoIt v3 zip
      run: Expand-Archive -Path autoit-v3.zip -DestinationPath autoit-v3
    - name: Compile the script
      run: ./autoit-v3/install/Aut2Exe/Aut2Exe_x64.exe /in TexModAutomator.au3 /out TexModAutomator.exe
